
POST http://localhost:80/api/bets
content-type: application/json
Host: bets-app.com.br

{
    "match": "1X-DC",
    "email": "joe@doe.com",
    "championship": "Uefa Champions League",
    "awayTeamScore": "2"
}

###

POST http://localhost:80/api/bets
content-type: application/json
Host: bets-app.com.br
apiKey: Ij6TSWYlZi1iGmKCzSzVSyJT6feLveAN

{
    "match": "1X-DC",
    "email": "joe@doe.com",
    "championship": "Uefa Champions League",
    "awayTeamScore": "2"
}

###
POST http://localhost:80/api/bets
content-type: application/json
Host: bets-app.com.br
Authorization: Basic am86YWRtaW4=

{
    "match": "1X-DC",
    "email": "joe@doe.com",
    "championship": "Uefa Champions League",
    "awayTeamScore": "2"
}
